
# tap repositories and their packages

tap homebrew/core
brew atuin
brew autoconf
brew azure-cli
brew bash
brew bat
brew ca-certificates
brew direnv
brew eza
brew fzf
brew gettext
brew gh
brew gum
brew jq
brew libevent
brew libgit2
brew libsodium
brew libssh2
brew libunistring
brew libuv
brew libyaml
brew llhttp
brew lpeg
brew luajit
brew luv
brew lz4
brew m4
brew mise
brew mpdecimal
brew ncurses
brew neovim
brew oniguruma
brew openssl
brew pcre2
brew pkgconf
brew prek
brew pyenv
brew python@3.13
brew python@3.14
brew readline
brew ripgrep
brew sqlite
brew starship
brew stow
brew termshot
brew thefuck
brew tmux
brew tree-sitter
brew unibilium
brew usage
brew utf8proc
brew uv
brew xz
brew zellij
brew zoxide
brew zstd

tap homebrew/cask
cask discord
cask font-fira-code-nerd-font
cask font-jetbrains-mono-nerd-font
cask font-mononoki-nerd-font
cask microsoft-azure-storage-explorer
cask orbstack
cask zoom

tap rcmdnk/file
brew brew-file

tap timescam/tap

# App Store applications
appstore 904280696 Things (3.22.11)
